---
title: "Final Project"
output: html_document
date: "2023-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
#library(gplots)
#library(maps) 
library(dplyr)  
#library(ggmap)
library(lubridate)
library(ggthemes)
library(RColorBrewer) 
library(sf)

```

```{r}

load('LAPOP.rda')
LAPOP <- da36562.0001
rm(da36562.0001)

sf_use_s2(FALSE)
#SouthAmericasf <- read_sf("vc965bq8111") %>%
#  group_by(name) %>%
#  summarise(geometry = st_combine(geometry)) %>%
#  mutate(name = stringr::str_to_lower(name))
  

library(rnaturalearth)
SouthAmericasf <- ne_countries(continent = 'South America',returnclass = 'sf') %>%
  mutate(name = stringr::str_to_lower(admin))

```

```{r}
SouthAmerica <- LAPOP %>% 
  filter(PAIS %in% c("(17) Argentina", "(10) Bolivia", "(08) Colombia", "(15) Brazil", "(12) Paraguay", "(14) Uruguay", "(11) Peru", "(13) Chile", "(09) Ecuador", "(16) Venezuela", "(27) Suriname")) %>% 
  mutate(PAIS = substr(PAIS, 6, 20))
rm(LAPOP)
```

```{r}
# HUMAN RIGHTS (To what extent do you think that citizens' basic rights are well protected by the political system of country?) (1= not at all, 7= a lot)

SouthAmericaB3 <- SouthAmerica %>% 
  select(YEAR, PAIS, B3) %>% 
  drop_na() %>% 
  group_by(PAIS) %>%
  mutate(total_resp_b3 = n()) %>% 
  filter( B3 >= 5) %>% 
  mutate(total_positive_b3 = n()) %>% 
  distinct(PAIS, .keep_all = TRUE) %>% 
  mutate(percent_good_b3 = 100 * total_positive_b3 / total_resp_b3) 


(SouthAmericasf %>% left_join(SouthAmericaB3 %>% mutate(PAIS = stringr::str_to_lower(PAIS)),by = c('name' = 'PAIS')) %>% 
    mutate(label = paste0(str_to_title(name),'\nPercent Agreement: ',round(percent_good_b3,2))) %>%
  ggplot() +
  geom_sf(aes(fill = percent_good_b3,text = label),linewidth = 0.05) +
  scale_fill_gradient(low="white", high = "darkblue", na.value = 'lightgrey') +
  theme_map() +
  theme(legend.background = element_blank()) +
  theme(legend.position = "right")
 ) %>% plotly::ggplotly(tooltip='text')
#Brianna: This is a way you can customize the tooltip

SouthAmericaB3 %>% 
  arrange(desc(percent_good_b3))

#  labs(title = "How Many South Americans   ", subtitle = "Respondents were asked: To what extent do you think that citizens' basic rights are well protected by the political system of country?", fill = "percent of respondants who answered that the political system highly protects their basic rights. % of Respondents with a Positive View of Basic Rights' Protection") 
```

```{r}
# LIFE SATISFACTION (In general how satisfied are you with your life?) (1 = very satisfied, 4 = very dissatisfied)

#Brianna heavily edited this; use example for others
SouthAmericaLS3 <- SouthAmerica %>% 
  mutate(PAIS = stringr::str_to_lower(PAIS)) %>%
  select(YEAR, PAIS, LS3) %>% 
  drop_na() %>% 
  mutate(LS3num = fct_recode(LS3, "1" = "(1) Very Satisfied", "2" = "(2) Somewhat Satisfied", "3" = "(3) Somewhat Dissatisfied", "4" = "(4) Very Dissatisfied")) %>%
  count(PAIS,YEAR,GoodLS3 = LS3num == "1") %>%
  group_by(PAIS,YEAR) %>%
  mutate(percent_good_ls3 = 100 * n / sum(n))  %>%
  filter(GoodLS3) 
  
  
SouthAmericaLS3 <- SouthAmericaLS3 %>%  right_join(expand_grid(PAIS =unique(SouthAmericasf$name), YEAR = unique(SouthAmericaLS3$YEAR)) %>% filter(!is.na(YEAR)))

SouthAmericas_map_data <- SouthAmericasf %>% left_join(SouthAmericaLS3, by = c('name' = 'PAIS'))

#These two lines, run in the console, fix the error about crs
#install.packages('devtools')
#devtools::install_version("transformr", version = "0.1.3")
library(transformr)
library(gganimate)
library(gifski)
map_anim <- 
  SouthAmericas_map_data %>% 
  arrange(YEAR) %>%
  mutate(LS3_Cat = fct_na_value_to_level(cut(percent_good_ls3,5),level='No Data')) %>%
  #filter(YEAR == 2012) %>%
  ggplot() +
  geom_sf(aes(fill = LS3_Cat),linewidth = .05) +
  labs(fill = ' Percent Satisifed with Life') +
  scale_fill_manual(values = c(colorRampPalette(c("white","firebrick"))(5),'lightgrey')) +
  theme_map() +
  theme(legend.background = element_blank()) +
  theme(legend.position = "right") +
  transition_states(YEAR) + labs(title = 'Percentage Satisfied with Life: {closest_state}')

animate(map_anim, nframes = 20, fps = 1, renderer = av_renderer())

#anim_save("ls3_map.gif",map_anim)


```

```{r}
# DEMOCRACY (Percent of people choosing "Democracy is preferable to any other form of government" and not "authoritarian " "it doesn't matter") 

SouthAmericaDEM2 <- SouthAmerica %>% 
  select(YEAR, PAIS, DEM2) %>% 
  drop_na() %>% 
  group_by(PAIS) %>% 
  mutate(total_resp_country = n()) %>% 
  filter(DEM2 == "(2) Democracy is preferable to any other form of government") %>% 
  mutate(total_dem2_country = n()) %>% 
  distinct(PAIS, .keep_all = TRUE) %>% 
  mutate(percent_good_dem2 = 100 * total_dem2_country / total_resp_country)

  
SouthAmericasf %>% left_join(SouthAmericaDEM2 %>% mutate(PAIS = stringr::str_to_lower(PAIS)),by = c('name' = 'PAIS')) %>% 
  ggplot() +
  geom_sf(aes(fill = percent_good_dem2))

SouthAmericaDEM2 %>% 
  select(PAIS, percent_good_dem2) %>% 
  arrange(desc(percent_good_dem2))
```

```{r}
# ECONOMIC SITUATION SOCT1 (How would you describe the country's economic situation?) (Percent of people that chose  "Good" or "Very Good" and not "fair, "bad" "very bad")


#shows NA values for this question (per country)
SouthAmerica %>% 
  select(YEAR, PAIS, SOCT1) %>% 
  group_by(PAIS) %>% 
  mutate(total_resp_country = n()) %>%
  mutate(num_na = sum(is.na(SOCT1))) %>% 
  distinct(PAIS, .keep_all = TRUE)

SouthAmericaSOCT1 <- SouthAmerica %>% 
  select(YEAR, PAIS, SOCT1) %>% 
  drop_na() %>% 
  group_by(PAIS) %>% 
  mutate(total_resp_country = n()) %>% 
  filter(SOCT1 %in% c("(2) Good", "(1) Very Good")) %>% 
  mutate(total_good_country = n()) %>% 
  distinct(PAIS, .keep_all = TRUE) %>% 
  mutate(percent_good_soct1 = 100 * total_good_country / total_resp_country)



SouthAmericasf %>% left_join(SouthAmericaSOCT1 %>% mutate(PAIS = stringr::str_to_lower(PAIS)),by = c('name' = 'PAIS')) %>% 
  ggplot() +
  geom_sf(aes(fill = percent_good_soct1))

SouthAmericaSOCT1 %>% 
  select(PAIS, percent_good_soct1) %>% 
  arrange(desc(percent_good_soct1))
```

```{r}
# scatterplots LS3 x B3:

LS3clean <- SouthAmericaLS3 %>% 
  select(PAIS, percent_good_ls3)

B3clean <- SouthAmericaB3 %>% 
  select(PAIS, percent_good_b3)

left_join(LS3clean, B3clean) %>% 
  ggplot(aes(x=percent_good_b3, y=percent_good_ls3, color = PAIS)) +
  geom_point() 
# change gkyph to name of country


# LS3 x DEM2:

DEM2clean <- SouthAmericaDEM2 %>% 
  select(PAIS, percent_good_dem2)

left_join(LS3clean, DEM2clean) %>% 
  ggplot(aes(x=percent_good_dem2, y=percent_good_ls3, color = PAIS)) +
  geom_point()


# LS3 x SOCT1

SOCT1clean <- SouthAmericaSOCT1 %>% 
  select(PAIS, percent_good_soct1)


left_join(LS3clean, SOCT1clean) %>% 
  ggplot(aes(x=percent_good_soct1, y=percent_good_ls3, color = PAIS)) +
  geom_point()
```

```{r}
#trying to show change over time in answers :)

# Life satisfaction 
LS3_over_time <- SouthAmerica %>% 
  select(YEAR, PAIS, LS3) %>% 
  drop_na() %>% 
  group_by(PAIS, YEAR) %>%
  mutate(LS3num = fct_recode(LS3, "1" = "(1) Very Satisfied", "2" = "(2) Somewhat Satisfied", "3" = "(3) Somewhat Dissatisfied", "4" = "(4) Very Dissatisfied")) %>%
  mutate(total_ls3 = n()) %>% 
  filter(LS3num == "1") %>% 
  mutate(total_good_ls3 = n()) %>% 
  distinct(PAIS, YEAR, .keep_all = TRUE) %>% 
  mutate(percent_good_ls3 = 100 * total_good_ls3 / total_ls3) %>% 
  select(PAIS, YEAR, percent_good_ls3, total_good_ls3, total_ls3)

LS3_over_time %>% 
  ggplot(aes(x=YEAR, y=percent_good_ls3)) +
  geom_point() +
  facet_wrap(~ PAIS)

LS3_over_time %>% 
  ggplot(aes(x=YEAR, y=percent_good_ls3, color=PAIS)) +
  geom_point()


# Gov protects basic rights
B3_over_time <- SouthAmerica %>% 
  select(YEAR, PAIS, B3) %>% 
  drop_na() %>% 
  group_by(PAIS, YEAR) %>%
  mutate(total_b3 = n()) %>% 
  filter(B3 >= 5) %>% 
  mutate(total_good_b3 = n()) %>% 
  distinct(PAIS, YEAR, .keep_all = TRUE) %>% 
  mutate(percent_good_b3 = 100 * total_good_b3 / total_b3) %>% 
  select(PAIS, YEAR, percent_good_b3, total_good_b3, total_b3)

B3_over_time %>% 
  ggplot(aes(x=YEAR, y=percent_good_b3)) +
  geom_point() +
  facet_wrap(~ PAIS)

B3_over_time %>% 
  ggplot(aes(x=YEAR, y=percent_good_b3, color=PAIS)) +
  geom_point()


# Democracy 
DEM2_over_time <- SouthAmerica %>% 
  select(YEAR, PAIS, DEM2) %>% 
  drop_na() %>% 
  group_by(PAIS, YEAR) %>% 
  mutate(total_dem2 = n()) %>% 
  filter(DEM2 == "(2) Democracy is preferable to any other form of government") %>% 
  mutate(total_good_dem2 = n()) %>% 
  distinct(PAIS, YEAR, .keep_all = TRUE) %>% 
  mutate(percent_good_dem2 = 100 * total_good_dem2 / total_dem2) %>% 
  select(PAIS, YEAR, percent_good_dem2, total_good_dem2, total_dem2)

DEM2_over_time %>% 
  ggplot(aes(x=YEAR, y=percent_good_dem2)) +
  geom_point() +
  facet_wrap(~ PAIS)

DEM2_over_time %>% 
  ggplot(aes(x=YEAR, y=percent_good_dem2, color=PAIS)) +
  geom_point()

 
#Economic situation 
SOCT1_over_time <- SouthAmerica %>% 
  select(YEAR, PAIS, SOCT1) %>% 
  drop_na() %>% 
  group_by(PAIS, YEAR) %>% 
  mutate(total_soct1 = n()) %>% 
  filter(SOCT1 %in% c("(2) Good", "(1) Very Good")) %>% 
  mutate(total_good_soct1 = n()) %>% 
  distinct(PAIS, YEAR, .keep_all = TRUE) %>% 
  mutate(percent_good_soct1 = 100 * total_good_soct1 / total_soct1) %>% 
  select(PAIS, YEAR, percent_good_soct1, total_good_soct1, total_soct1)

SOCT1_over_time %>% 
  ggplot(aes(x=YEAR, y=percent_good_soct1)) +
  geom_point() +
  facet_wrap(~ PAIS)

SOCT1_over_time %>% 
  ggplot(aes(x=YEAR, y=percent_good_soct1, color=PAIS)) +
  geom_point()

```

```{r}

# new data set: all 4 questions over time and visuals

questions_over_time <- left_join(LS3_over_time, B3_over_time)
questions_over_time <- left_join(questions_over_time, DEM2_over_time)
questions_over_time <- left_join(questions_over_time, SOCT1_over_time)


questions_over_time %>% 
  ggplot(aes(x=percent_good_ls3, y=percent_good_dem2, color=PAIS)) +
  geom_point() +
  facet_wrap(~ YEAR)

questions_over_time <- questions_over_time %>% 
  mutate(YearCat = cut(YEAR, c(2004,2009,2015), right = FALSE, labels = c('2004-08','2009-14')))

# first half decade
questions_over_time %>% 
  filter(YearCat == "2004-08") %>% 
  ggplot(aes(y=percent_good_ls3, x=percent_good_dem2, color=YEAR)) +
  geom_text(aes(label =PAIS))

questions_over_time %>% 
  filter(YearCat == "2004-08") %>% 
  ggplot(aes(y=percent_good_ls3, x=percent_good_soct1, color=YEAR)) +
  geom_text(aes(label =PAIS))


# animated basic rights and life satisfaction over time for all countries!
library(gganimate)
pp_anim <- questions_over_time %>% 
  #filter(YearCat == "2004-08") %>% 
  ggplot(aes(y=percent_good_ls3, x=percent_good_b3, color=PAIS)) +
  geom_text(aes(label =PAIS)) + 
  geom_hline(yintercept = 40) +
  geom_vline(xintercept = 35) + theme_classic() + transition_states(YEAR)

animate(pp_anim, nframes = 20, fps = 1,renderer = av_renderer())
```

```{r}
# animated dem2 and life satisfaction over time for all countries!
library(gganimate)
pp_anim <- questions_over_time %>% 
  ggplot(aes(y=percent_good_ls3, x=percent_good_dem2, color=PAIS)) +
  geom_text(aes(label =PAIS)) + 
  geom_hline(yintercept = 40) +
  geom_vline(xintercept = 50) + theme_classic() + transition_states(YEAR)

animate(pp_anim, nframes = 20, fps = 1,renderer = av_renderer())
```

```{r}
# animated soct1 and life satisfaction over time for all countries!
library(gganimate)
pp_anim <- questions_over_time %>% 
  ggplot(aes(y=percent_good_ls3, x=percent_good_soct1, color=PAIS)) +
  geom_text(aes(label =PAIS)) + 
  geom_hline(yintercept = 40) +
  geom_vline(xintercept = 50) + theme_classic() + transition_states(YEAR)

animate(pp_anim, nframes = 20, fps = 1,renderer = av_renderer())
```

```{r}
#if we do this for one country (case study): add geom_path to shwo the journey

# second half decade
questions_over_time %>% 
  filter(YearCat == "2009-14") %>% 
  ggplot(aes(y=percent_good_ls3, x=percent_good_dem2, color=YEAR)) +
  geom_text(aes(label =PAIS))

questions_over_time %>% 
  filter(YearCat == "2009-14") %>% 
  ggplot(aes(y=percent_good_ls3, x=percent_good_soct1, color=YEAR)) +
  geom_text(aes(label =PAIS))

questions_over_time %>% 
  filter(YearCat == "2009-14") %>% 
  ggplot(aes(y=percent_good_ls3, x=percent_good_b3, color=YEAR)) +
  geom_text(aes(label =PAIS))


#pivot longer:
questions_over_time %>% 
  select(YEAR, PAIS, percent_good_ls3, percent_good_b3, percent_good_dem2, percent_good_soct1, YearCat) %>% 
  pivot_longer(3:6, names_to = "Question", values_to = "Percent Good", values_drop_na = FALSE) %>% 
  filter(PAIS == "Venezuela") %>% 
  ggplot(aes(x=`Percent Good`, fill =Question)) +
  geom_density() +
  facet_grid(~YearCat)


questions_over_time %>% 
  select(YEAR, PAIS, percent_good_ls3, percent_good_b3, percent_good_dem2, percent_good_soct1, YearCat) %>% 
  pivot_longer(3:6, names_to = "Question", values_to = "Percent Good", values_drop_na = FALSE) %>% 
  filter(PAIS == "Bolivia") %>% 
  ggplot(aes(x=`Percent Good`, fill =Question)) +
  geom_density() +
  facet_grid(~YearCat)


questions_over_time %>% 
  select(YEAR, PAIS, percent_good_ls3, percent_good_b3, percent_good_dem2, percent_good_soct1, YearCat) %>% 
  pivot_longer(3:6, names_to = "Question", values_to = "Percent Good", values_drop_na = FALSE) %>% 
  filter(PAIS == "Venezuela") %>% 
  ggplot(aes(x=YEAR, y=`Percent Good`)) +
  geom_point() + facet_grid(~Question)

questions_over_time %>% 
  select(YEAR, PAIS, percent_good_ls3, percent_good_b3, percent_good_dem2, percent_good_soct1, YearCat) %>% 
  pivot_longer(3:6, names_to = "Question", values_to = "Percent Good", values_drop_na = FALSE) %>% 
  filter(PAIS == "Bolivia") %>% 
  ggplot(aes(x=YEAR, y=`Percent Good`)) +
  geom_point() + facet_grid(~Question)

questions_over_time %>% 
  select(YEAR, PAIS, percent_good_ls3, percent_good_b3, percent_good_dem2, percent_good_soct1, YearCat) %>% 
  pivot_longer(3:6, names_to = "Question", values_to = "Percent Good", values_drop_na = FALSE) %>% 
  filter(PAIS == "Venezuela") %>% 
  ggplot(aes(x=YEAR, y=`Percent Good`, color=Question)) +
  geom_point() + geom_line()

questions_over_time %>% 
  select(YEAR, PAIS, percent_good_ls3, percent_good_b3, percent_good_dem2, percent_good_soct1, YearCat) %>% 
  pivot_longer(3:6, names_to = "Question", values_to = "Percent Good", values_drop_na = FALSE) %>% 
  filter(PAIS == "Bolivia") %>% 
  ggplot(aes(x=YEAR, y=`Percent Good`, color=Question)) +
  geom_point() + geom_line()
```

```{r}
#VENEZUELA 

questions_over_time %>% 
  filter(PAIS == "Venezuela") %>% 
  ggplot(aes(y=percent_good_ls3, x=YEAR, color=percent_good_dem2)) +
  geom_text(aes(label =PAIS))

questions_over_time %>% 
  filter(PAIS == "Venezuela") %>% 
  ggplot(aes(y=percent_good_ls3, x=YEAR, color=percent_good_soct1)) +
  geom_text(aes(label =PAIS))


questions_over_time %>% 
  filter(PAIS == "Venezuela") %>% 
  ggplot(aes(y=percent_good_ls3, x=YEAR, color=percent_good_b3)) +
  geom_text(aes(label =PAIS))

```



# Final Visuals 
### (in progress, but the ones we'll most likley use)

```{r}
# LIFE SATISFACTION map animination (In general how satisfied are you with your life?) (1 = very satisfied, 4 = very dissatisfied)


# Explicitly categorize percent good and include NA as a category
library(gganimate)
SouthAmericaLS3 <- SouthAmerica %>% 
  mutate(PAIS = stringr::str_to_lower(PAIS)) %>%
  select(YEAR, PAIS, LS3) %>% 
  drop_na() %>% 
  mutate(LS3num = fct_recode(LS3, "1" = "(1) Very Satisfied", "2" = "(2) Somewhat Satisfied", "3" = "(3) Somewhat Dissatisfied", "4" = "(4) Very Dissatisfied")) %>%
  count(PAIS,YEAR,GoodLS3 = LS3num == "1") %>%
  group_by(PAIS,YEAR) %>%
  mutate(percent_good_ls3 = 100 * n / sum(n))  %>%
  filter(GoodLS3) 
  
SouthAmericaLS3 <- SouthAmericaLS3 %>%  right_join(expand_grid(PAIS =unique(SouthAmericasf$name), YEAR = unique(SouthAmericaLS3$YEAR)) %>% filter(!is.na(YEAR)))

SouthAmericas_map_data <- SouthAmericasf %>% left_join(SouthAmericaLS3, by = c('name' = 'PAIS'))

#These two lines, run in the console, fix the error about crs
#install.packages('devtools')
#devtools::install_version("transformr", version = "0.1.3")
library(transformr)
library(gganimate)
library(gifski)
map_anim <- 
  SouthAmericas_map_data %>% 
  arrange(YEAR) %>%
  mutate(LS3_Cat = factor(percent_good_ls3)) %>% 
  mutate(LS3_Cat = fct_rev(LS3_Cat)) %>% 
  mutate(LS3_Cat = fct_na_value_to_level(cut(percent_good_ls3,5),level='No Data')) %>%
  ggplot() +
  geom_sf(aes(fill = LS3_Cat),linewidth = .05) +
  labs(fill = '% of Respondents with High Life Satisfaction') +
  scale_fill_manual(values = c(colorRampPalette(c("white","darkgreen"))(5),'lightgrey')) +
  theme_map() +
  theme(legend.background = element_blank()) +
  theme(legend.position = "right") +
  transition_states(YEAR) + labs(title = 'High Life Satisfaction in South America: {closest_state}')

animate(map_anim, nframes = 20, fps = 1, renderer = gifski_renderer())

anim_save("ls3_map.gif",map_anim)
```


```{r}
# Animated basic rights and life satisfaction over time for all countries! - Inbal
library(gganimate)
pp_anim <- questions_over_time %>% 
  ggplot(aes(y=percent_good_ls3, x=percent_good_b3, color=PAIS)) +
  geom_text(aes(label =PAIS)) + 
  geom_hline(yintercept = 40) +
  geom_vline(xintercept = 35) + theme_classic() + transition_states(YEAR) + labs(title = "High Life Satisfaction and Basic Right Protection Over Time in South America", y="Percent of Respondents who Reported High Life Satisfaction", x="Percent of Respondents who reported", color="Country")

animate(pp_anim, renderer = gifski_renderer())



```

```{r}
# LS3 all countries over time animation - Inbal
library(gganimate)
pp_anim <- questions_over_time %>% 
  select(YEAR, PAIS, percent_good_ls3, percent_good_b3, percent_good_dem2, percent_good_soct1) %>% 
  pivot_longer(3:6, names_to = "Question", values_to = "Percent Good", values_drop_na = FALSE) %>% 
  filter(Question == "percent_good_ls3") %>% 
  ggplot(aes(x=YEAR, y=`Percent Good`, color=PAIS, group = PAIS)) +
  geom_point() + geom_line() + transition_reveal(YEAR) + labs(title = "High Life Satisfaction Over Time in South America", y="Percent of Respondents who Reported High Life Satisfaction", x="Year", color="Country")

animate(pp_anim, renderer = gifski_renderer())

#Brianna: I think the issue is that Suriname has the travel the farthest and the interpolation is messing up. I don't think there is an easy fix except to use a looping Gif...
```

```{r}
# Scatter plot, faceted by country, LS3 over time - Maya

questions_over_time %>%
  ggplot(aes(x= YEAR, y=percent_good_ls3)) +
  geom_point(color = "darkmagenta") +
  geom_line(color = "darkmagenta") +
  facet_wrap(~PAIS) +
  labs(x = "Year", y = "Respondents who Reported High Life Satisfaction (%)", title = "Positive Perception of Life Satisfaction Over Time in South America")+
   theme_classic()+
  theme(axis.text.x = element_text(angle = 45, hjust=.7))
```

```{r}

# Bolivia's LS3 + B3 over time animiation - Flor
library(gganimate)
pp_anim <- questions_over_time %>%
  filter(PAIS == "Bolivia") %>%
  ggplot(aes(y=percent_good_ls3, x=percent_good_b3, group=PAIS)) +
    geom_point() + geom_path(color = "darkmagenta") +
  #geom_text(aes(label =PAIS)) +
  theme_classic() +
  labs(title = "Bolivia's High Life Satisfaction and Govt. Protection of Basic Rights", subtitle = "From 2004-2014", x = "Participants who Reported Good Government Protection of Basic Rights (%)" ,y = "Participants who Reported High Life Satisfaction (%)") +
 transition_reveal(YEAR)
animate(pp_anim, nframes = 20, fps = 1,renderer = av_renderer())

```

```{r}
# Scatter plot of Bolivia with all 4 questions over time - Flor
questions_over_time_Bolivia <- questions_over_time
colnames(questions_over_time_Bolivia)[colnames(questions_over_time_Bolivia) == "percent_good_ls3"] <- "High life satisfaction"
colnames(questions_over_time_Bolivia)[colnames(questions_over_time_Bolivia) == "percent_good_b3"] <- "Govt. protects basic rights"
colnames(questions_over_time_Bolivia)[colnames(questions_over_time_Bolivia) == "percent_good_dem2"] <- "Democracy is most preferable"
colnames(questions_over_time_Bolivia)[colnames(questions_over_time_Bolivia) == "percent_good_soct1"] <- "Good economic situation"
questions_over_time_Bolivia %>%
  select(c("YEAR", "PAIS", "Good economic situation", "Govt. protects basic rights", "Democracy most preferable",  "High life satisfaction")) %>%
  pivot_longer(3:6, names_to = "Categories", values_to = "Percent Good", values_drop_na = FALSE) %>%
  filter(PAIS == "Bolivia") %>%
  ggplot(aes(x=YEAR, y=`Percent Good`, color=Categories)) +
  geom_point() + geom_line() +
  labs(title = "Bolivia's Positive Perceptions", subtitle = "Life Satisfaction, Democracy, Basic Rights, and the Economy From 2004 - 2014", x= "Year", y= "Pecrentage of Agreement",fill = '') +
  theme_classic() + scale_color_brewer(palette = "Pastel2") +
  theme(plot.title = element_text(face = "bold"))

```

